/**
	Copyright 2014 [BFR]
	
	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at
	
	    http://www.apache.org/licenses/LICENSE-2.0
	
	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.
**/
package org.bfr.querytools.msr.driver;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.5
//
// Date Of Creation: 4/16/2014 12:56:58 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class AnalysisResult implements KvmSerializable
{

	public int totalFreeChannels;
	public int maxContiguousWidth;
	public int medianContiguousWidth;
	public int minContiguousWidth;
	public int uHFTotalFreeChannels;
	public int uHFMaxContiguousWidth;
	public int uHFMedianContiguousWidth;
	public int uHFMinContiguousWidth;
	public VectorBoolean channelMap;

	public AnalysisResult()
	{
	}

	public AnalysisResult(SoapObject soapObject)
	{
		if (soapObject == null)
			return;
		if (soapObject.hasProperty("TotalFreeChannels"))
		{
			Object obj = soapObject.getProperty("TotalFreeChannels");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class))
			{
				SoapPrimitive j = (SoapPrimitive) obj;
				totalFreeChannels = Integer.parseInt(j.toString());
			} else if (obj != null && obj instanceof Number)
			{
				totalFreeChannels = (Integer) obj;
			}
		}
		if (soapObject.hasProperty("MaxContiguousWidth"))
		{
			Object obj = soapObject.getProperty("MaxContiguousWidth");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class))
			{
				SoapPrimitive j = (SoapPrimitive) obj;
				maxContiguousWidth = Integer.parseInt(j.toString());
			} else if (obj != null && obj instanceof Number)
			{
				maxContiguousWidth = (Integer) obj;
			}
		}
		if (soapObject.hasProperty("MedianContiguousWidth"))
		{
			Object obj = soapObject.getProperty("MedianContiguousWidth");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class))
			{
				SoapPrimitive j = (SoapPrimitive) obj;
				medianContiguousWidth = Integer.parseInt(j.toString());
			} else if (obj != null && obj instanceof Number)
			{
				medianContiguousWidth = (Integer) obj;
			}
		}
		if (soapObject.hasProperty("MinContiguousWidth"))
		{
			Object obj = soapObject.getProperty("MinContiguousWidth");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class))
			{
				SoapPrimitive j = (SoapPrimitive) obj;
				minContiguousWidth = Integer.parseInt(j.toString());
			} else if (obj != null && obj instanceof Number)
			{
				minContiguousWidth = (Integer) obj;
			}
		}
		if (soapObject.hasProperty("UHFTotalFreeChannels"))
		{
			Object obj = soapObject.getProperty("UHFTotalFreeChannels");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class))
			{
				SoapPrimitive j = (SoapPrimitive) obj;
				uHFTotalFreeChannels = Integer.parseInt(j.toString());
			} else if (obj != null && obj instanceof Number)
			{
				uHFTotalFreeChannels = (Integer) obj;
			}
		}
		if (soapObject.hasProperty("UHFMaxContiguousWidth"))
		{
			Object obj = soapObject.getProperty("UHFMaxContiguousWidth");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class))
			{
				SoapPrimitive j = (SoapPrimitive) obj;
				uHFMaxContiguousWidth = Integer.parseInt(j.toString());
			} else if (obj != null && obj instanceof Number)
			{
				uHFMaxContiguousWidth = (Integer) obj;
			}
		}
		if (soapObject.hasProperty("UHFMedianContiguousWidth"))
		{
			Object obj = soapObject.getProperty("UHFMedianContiguousWidth");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class))
			{
				SoapPrimitive j = (SoapPrimitive) obj;
				uHFMedianContiguousWidth = Integer.parseInt(j.toString());
			} else if (obj != null && obj instanceof Number)
			{
				uHFMedianContiguousWidth = (Integer) obj;
			}
		}
		if (soapObject.hasProperty("UHFMinContiguousWidth"))
		{
			Object obj = soapObject.getProperty("UHFMinContiguousWidth");
			if (obj != null && obj.getClass().equals(SoapPrimitive.class))
			{
				SoapPrimitive j = (SoapPrimitive) obj;
				uHFMinContiguousWidth = Integer.parseInt(j.toString());
			} else if (obj != null && obj instanceof Number)
			{
				uHFMinContiguousWidth = (Integer) obj;
			}
		}
		if (soapObject.hasProperty("ChannelMap"))
		{
			SoapObject j = (SoapObject) soapObject.getProperty("ChannelMap");
			channelMap = new VectorBoolean(j);
		}
	}

	@Override
	public Object getProperty(int arg0)
	{
		switch (arg0)
		{
		case 0:
			return totalFreeChannels;
		case 1:
			return maxContiguousWidth;
		case 2:
			return medianContiguousWidth;
		case 3:
			return minContiguousWidth;
		case 4:
			return uHFTotalFreeChannels;
		case 5:
			return uHFMaxContiguousWidth;
		case 6:
			return uHFMedianContiguousWidth;
		case 7:
			return uHFMinContiguousWidth;
		case 8:
			return channelMap;
		}
		return null;
	}

	@Override
	public int getPropertyCount()
	{
		return 9;
	}

	@Override
	public void getPropertyInfo(int index,
			@SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
	{
		switch (index)
		{
		case 0:
			info.type = PropertyInfo.INTEGER_CLASS;
			info.name = "TotalFreeChannels";
			break;
		case 1:
			info.type = PropertyInfo.INTEGER_CLASS;
			info.name = "MaxContiguousWidth";
			break;
		case 2:
			info.type = PropertyInfo.INTEGER_CLASS;
			info.name = "MedianContiguousWidth";
			break;
		case 3:
			info.type = PropertyInfo.INTEGER_CLASS;
			info.name = "MinContiguousWidth";
			break;
		case 4:
			info.type = PropertyInfo.INTEGER_CLASS;
			info.name = "UHFTotalFreeChannels";
			break;
		case 5:
			info.type = PropertyInfo.INTEGER_CLASS;
			info.name = "UHFMaxContiguousWidth";
			break;
		case 6:
			info.type = PropertyInfo.INTEGER_CLASS;
			info.name = "UHFMedianContiguousWidth";
			break;
		case 7:
			info.type = PropertyInfo.INTEGER_CLASS;
			info.name = "UHFMinContiguousWidth";
			break;
		case 8:
			info.type = PropertyInfo.VECTOR_CLASS;
			info.name = "ChannelMap";
			break;
		}
	}

	@Override
	public void setProperty(int arg0, Object arg1)
	{
	}

}
