/**
	Copyright 2014 [BFR]
	
	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at
	
	    http://www.apache.org/licenses/LICENSE-2.0
	
	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.
**/
package org.bfr.querytools.msr.driver;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.5
//
// Date Of Creation: 4/16/2014 12:56:58 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import java.util.Hashtable;
import java.util.Vector;

import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import org.ksoap2.serialization.SoapObject;

@SuppressWarnings("serial")
public class VectorLocation extends Vector<Location> implements KvmSerializable
{

	public VectorLocation()
	{
	}

	public VectorLocation(SoapObject soapObject)
	{
		if (soapObject == null)
			return;
		if (soapObject != null)
		{
			int size = soapObject.getPropertyCount();
			for (int i0 = 0; i0 < size; i0++)
			{
				Object obj = soapObject.getProperty(i0);
				if (obj != null && obj.getClass().equals(SoapObject.class))
				{
					SoapObject j0 = (SoapObject) soapObject.getProperty(i0);
					Location j1 = new Location(j0);
					add(j1);
				}
			}
		}
	}

	@Override
	public Object getProperty(int arg0)
	{
		return this.get(arg0);
	}

	@Override
	public int getPropertyCount()
	{
		return this.size();
	}

	@Override
	public void getPropertyInfo(int index,
			@SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info)
	{
		info.name = "location";
		info.type = Location.class;
	}

	@Override
	public void setProperty(int arg0, Object arg1)
	{
	}

}
