/**
	Copyright 2014 [BFR]
	
	Licensed under the Apache License, Version 2.0 (the "License");
	you may not use this file except in compliance with the License.
	You may obtain a copy of the License at
	
	    http://www.apache.org/licenses/LICENSE-2.0
	
	Unless required by applicable law or agreed to in writing, software
	distributed under the License is distributed on an "AS IS" BASIS,
	WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
	See the License for the specific language governing permissions and
	limitations under the License.
**/
package org.bfr.querytools.msr.driver;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.5
//
// Date Of Creation: 4/16/2014 12:56:58 PM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
public class WS_Enums
{

	public enum SoapProtocolVersion
	{
		Default(0), Soap11(1), Soap12(2);

		private int code;

		SoapProtocolVersion(int code)
		{
			this.code = code;
		}

		public int getCode()
		{
			return code;
		}

		public static SoapProtocolVersion fromString(String str)
		{
			if (str.equals("Default"))
				return Default;
			if (str.equals("Soap11"))
				return Soap11;
			if (str.equals("Soap12"))
				return Soap12;
			return null;
		}
	}

	public enum IncumbentType
	{
		DTV(0), LPTV(1), Microphone(2), DC(3), LD(4), TRANSLATOR(5), CA(6), DS(
				7), Unknown(8);

		private int code;

		IncumbentType(int code)
		{
			this.code = code;
		}

		public int getCode()
		{
			return code;
		}

		public static IncumbentType fromString(String str)
		{
			if (str.equals("DTV"))
				return DTV;
			if (str.equals("LPTV"))
				return LPTV;
			if (str.equals("Microphone"))
				return Microphone;
			if (str.equals("DC"))
				return DC;
			if (str.equals("LD"))
				return LD;
			if (str.equals("TRANSLATOR"))
				return TRANSLATOR;
			if (str.equals("CA"))
				return CA;
			if (str.equals("DS"))
				return DS;
			if (str.equals("Unknown"))
				return Unknown;
			return null;
		}
	}
}
